### ISSUE TITLE
Add parallelization

### ISSUE THREAD

**Issue by osorensen** [Lifebrain/metagam#20]
Replace functions from the purrr package with functions from the furrr package. Then the user can run the algorithm in parallel using something like this:

```r
library(future)
plan(multiprocess)
fits <- metagam(...)
```

**Comment by osorensen** [comment]
Here is an example how it can be done: https://cran.r-project.org/package=jstor

**Comment by osorensen** [comment]
I tried, and simply replacing `purrr::map*` by `furrr::future_map*` was not enough. It seems like we have to make sure the metagam functions are exported to each worker. Need to read up before trying again.

**Comment by HenrikBengtsson** [comment]
See issue #30 for the solution
