### ISSUE TITLE
multisession futures: Error in UseMethod("predict") : no applicable method for 'predict' applied to an object of class "c('rma.uni', 'rma')"

### ISSUE THREAD

**Issue by HenrikBengtsson** [Lifebrain/metagam#30]
Hi, while running revdep checks on future with environment variable `R_FUTURE_PLAN=multisession` set I force all package checks to use 'multisession' futures instead of the default 'sequential'.  Doing so, caught a bug in your:

https://github.com/Lifebrain/metagam/blob/60eb2e56b8fb5f34eb2dc8f3c8467cf46321afdd/R/metagam.R#L94-L115

[resulting in the following error](https://github.com/HenrikBengtsson/future/blob/develop/revdep/R_FUTURE_PLAN%3Dmultisession/problems.md#metagam):

```
 meta_analysis <- metagam(models, terms = "s(x1)", grid_size = 30)
Error in UseMethod("predict") : 
  no applicable method for 'predict' applied to an object of class "c('rma.uni', 'rma')"
Calls: metagam ... resolve.list -> signalConditionsASAP -> signalConditions
Execution halted
```

You can replicate this yourself by running:

```r
library(future)
plan(multisession, workers = 2)
example("metagam", package = "metagam")
```

The problem is that the background workers don't have 'metafor' loaded causing `predict()` for 'rma' objects not to be available.  To fix this, you can tell the future framework that you need this package as:

```r
 cohort_estimates <- furrr::future_map_dfr(models, function(x) { 
   ...
 }, .id = "model", .options = furrr_options(packages = "metafor")) 
```

This is one of these cases where it's really hard for future/globals to infer that this package is needed and you basically need to guide it this way.

**Comment by osorensen** [comment]
Thanks a lot for this comprehensive description of how to solve the issue! I think I was able to fix it.
